"""Finite differences vs binomial trees vs the Black–Scholes formula.

Tables of option values across spot prices for two American puts (with and
without dividends) and an American call on a dividend-paying asset, and a
figure of the value curve and the early-exercise premium.

Run:  python scripts/compare_methods.py
"""

from __future__ import annotations

import numpy as np
from _common import BLUE, INK_2, MUTED, ORANGE, md_table, plt, save, write_md

from americanfd import Option, binomial_price, bs_price, solve_fd

M = N = 800
CASES = {
    "Seydel Ex. 1.6 — American put, no dividends (K=50, T=5/12, r=10%, σ=40%)": (
        Option(K=50.0, T=5 / 12, r=0.1, sigma=0.4, kind="put"),
        [35.0, 40.0, 45.0, 50.0, 55.0, 60.0, 70.0],
    ),
    "Seydel Tab. 4.1 — American put, dividends (K=10, T=1, r=25%, σ=60%, δ=20%)": (
        Option(K=10.0, T=1.0, r=0.25, sigma=0.6, div=0.2, kind="put"),
        [6.0, 8.0, 10.0, 12.0, 14.0],
    ),
    "Seydel Fig. 4.9 — American call, dividends (K=10, T=1, r=25%, σ=60%, δ=20%)": (
        Option(K=10.0, T=1.0, r=0.25, sigma=0.6, div=0.2, kind="call"),
        [6.0, 8.0, 10.0, 12.0, 14.0, 20.0],
    ),
}

sections = []
for title, (opt, spots) in CASES.items():
    res = solve_fd(opt, M, N)
    rows = []
    for S in spots:
        fd = float(res.price(S))
        bbsr = binomial_price(S, opt, n=10_000, method="bbsr")
        crr = binomial_price(S, opt, n=1_000, method="crr")
        eu = float(bs_price(S, opt))
        rows.append(
            [
                f"{S:g}",
                f"{fd:.6f}",
                f"{bbsr:.6f}",
                f"{crr:.6f}",
                f"{abs(fd - bbsr):.1e}",
                f"{eu:.6f}",
                f"{fd - eu:.6f}",
            ]
        )
    sf = res.exercise_boundary_t0
    head = ["S", f"FD ({M}×{N})", "BBSR (N=10⁴)", "CRR (N=10³)", "abs(FD − BBSR)",
            "European (BS)", "early-exercise premium"]  # fmt: skip
    sections.append(
        f"### {title}\n\nExercise boundary at t = 0 (grid point): S_f ≈ {sf:.3f}\n\n"
        + md_table(head, rows)
    )
    print("done:", title)

write_md(
    "comparison.md",
    "# Method comparison\n\nGenerated by `scripts/compare_methods.py`. FD = Crank–Nicolson "
    "with Rannacher start-up and PSOR. BBSR = binomial Black–Scholes with Richardson "
    "extrapolation; CRR = plain Cox–Ross–Rubinstein tree (note its O(1/N) error).\n\n"
    + "\n\n".join(sections),
)

# ----------------------------------------------------------------------------- figure
opt = CASES[next(iter(CASES))][0]
res = solve_fd(opt, M, N)
S = np.linspace(20.0, 90.0, 400)
am = res.price(S)
eu = bs_price(S, opt)
sf = res.exercise_boundary_t0
dots = np.array([30.0, 40.0, 50.0, 60.0, 70.0, 80.0])
dots_v = [binomial_price(s, opt, n=4000) for s in dots]

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(11, 4.2))
ax1.plot(S, opt.payoff(S), color=MUTED, lw=1.2, ls="--", label="payoff (K − S)⁺")
ax1.plot(S, eu, color=ORANGE, label="European (Black–Scholes)")
ax1.plot(S, am, color=BLUE, label="American (finite differences)")
ax1.plot(dots, dots_v, ls="none", marker="o", mfc="white", mec=INK_2, mew=1.3,
         label="American (BBSR binomial)")  # fmt: skip
ax1.axvline(sf, color=MUTED, lw=1)
ax1.annotate(f"S_f(0) ≈ {sf:.1f}", (sf, 1.0), xytext=(-6, 0), textcoords="offset points",
             ha="right", color=INK_2, fontsize=8.5)  # fmt: skip
ax1.set(xlabel="spot S", ylabel="option value at t = 0", xlim=(20, 90), ylim=(-0.5, 31),
        title="American vs European put (K = 50)")  # fmt: skip
ax1.legend(loc="upper right")

ax2.plot(S, am - eu, color=BLUE)
ax2.axvline(sf, color=MUTED, lw=1)
ax2.set(xlabel="spot S", ylabel="V_American − V_European",
        title="Early-exercise premium", xlim=(20, 90))  # fmt: skip
ax2.annotate("stopping region:\nV = K − S", (22, (am - eu)[5] * 0.55), color=INK_2, fontsize=8.5)
save(fig, "american_vs_european.png")
