"""Grid-convergence study (Seydel §4.7).

* European put: errors of price, Delta, Gamma, Theta at S = K against the
  Black–Scholes formula; observed order p = log2(e(m) / e(2m)).
* American put (Seydel Example 1.6): price error against a BBSR binomial
  reference for several schemes, plus Richardson extrapolation
  eta* ~ eta(m) + (eta(m) - eta(m/2)) / 3.
* PSOR vs Brennan–Schwartz: agreement, sweeps per step and run time.

Run:  python scripts/convergence.py      (about a minute without numba)
"""

from __future__ import annotations

import time

import numpy as np
from _common import AQUA, BLUE, INK_2, MUTED, ORANGE, VIOLET, md_table, plt, save, write_md

from americanfd import Option, binomial_price, bs_greeks, solve_fd

GRIDS = [50, 100, 200, 400, 800, 1600, 3200]


def orders(err):
    err = np.abs(np.asarray(err, float))
    return [""] + [f"{np.log2(a / b):.2f}" for a, b in zip(err[:-1], err[1:], strict=True)]


def fmt(v):
    return f"{v:.2e}"


# ----------------------------------------------------------------------------- European
eu = Option(K=100.0, T=0.5, r=0.05, sigma=0.25, div=0.02, kind="put", style="european")
S0 = 100.0
exact = bs_greeks(S0, eu)
eu_err = {k: [] for k in ("price", "delta", "gamma", "theta")}
eu_grids = GRIDS[:-1]
for m in eu_grids:
    g = solve_fd(eu, m, m).greeks(S0)
    for k in eu_err:
        eu_err[k].append(abs(getattr(g, k) - getattr(exact, k)))

eu_rows = []
o = {k: orders(v) for k, v in eu_err.items()}
for i, m in enumerate(eu_grids):
    row = [m]
    for k in eu_err:
        row += [fmt(eu_err[k][i]), o[k][i]]
    eu_rows.append(row)

# ----------------------------------------------------------------------------- American
am = Option(K=50.0, T=5 / 12, r=0.1, sigma=0.4, kind="put", style="american")
t0 = time.perf_counter()
ref = binomial_price(50.0, am, n=40_000)
print(f"BBSR reference {ref:.9f} ({time.perf_counter() - t0:.1f}s)")

variants = {
    "CN + Rannacher (default)": dict(),
    "CN, no start-up smoothing": dict(rannacher=0),
    "Fully implicit (theta = 1)": dict(theta=1.0, rannacher=0),
    "Seydel's setup: CN, x in [-5, 5]": dict(rannacher=0, half_width=5.0),
}
am_val = {name: [] for name in variants}
for name, kw in variants.items():
    for m in GRIDS:
        am_val[name].append(solve_fd(am, m, m, lcp="brennan-schwartz", **kw).price(50.0))
    print("done:", name)

am_err = {k: np.abs(np.array(v) - ref) for k, v in am_val.items()}
best = np.array(am_val["CN + Rannacher (default)"])
extrap = best[1:] + (best[1:] - best[:-1]) / 3.0
extrap_err = np.abs(extrap - ref)

am_rows = []
names = list(variants)
o_am = {k: orders(v) for k, v in am_err.items()}
o_ex = [""] + orders(extrap_err)
for i, m in enumerate(GRIDS):
    row = [m, f"{best[i]:.7f}"]
    for k in names[:3]:
        row += [fmt(am_err[k][i]), o_am[k][i]]
    row += [fmt(extrap_err[i - 1]) if i else "", o_ex[i]]
    am_rows.append(row)

# ----------------------------------------------------------------------------- PSOR
psor_rows = []
for m in (100, 200, 400, 800, 1600):
    a = solve_fd(am, m, m, lcp="psor")
    b = solve_fd(am, m, m, lcp="brennan-schwartz")
    psor_rows.append(
        [
            m,
            fmt(np.abs(a.V - b.V).max()),
            f"{np.mean(a.psor_sweeps):.1f}",
            max(a.psor_sweeps),
            f"{a.elapsed:.2f}",
            f"{b.elapsed:.2f}",
        ]
    )
    print("psor", m)

# ----------------------------------------------------------------------------- write
eu_head = ["m = n", "price err", "p", "Delta err", "p", "Gamma err", "p", "Theta err", "p"]
am_head = ["m = n", "V (CN+R)", "CN+Rannacher", "p", "CN plain", "p", "implicit", "p"]
am_head += ["extrapolated", "p"]
ps_head = ["m = n", "max abs diff of V", "mean sweeps", "max sweeps", "PSOR, s"]
ps_head += ["Brennan–Schwartz, s"]
eu_table = md_table(eu_head, eu_rows)
am_table = md_table(am_head, am_rows)
psor_table = md_table(ps_head, psor_rows)
md = f"""# Convergence study

Generated by `scripts/convergence.py`. Grid: m space intervals = n time steps.

## European put vs Black–Scholes

K = S = 100, T = 0.5, r = 5%, sigma = 25%, dividend yield 2%; Crank–Nicolson with
Rannacher start-up. `p` is the observed order log2(e(m)/e(2m)).

{eu_table}

## American put vs binomial reference

Seydel Example 1.6: K = S = 50, T = 5/12, r = 10%, sigma = 40%.
Reference: BBSR binomial tree, N = 40 000 steps, V = {ref:.7f}
(its own error is below 1e-6).
Extrapolated: Richardson with p = 2 from grids m/2 and m (Seydel 4.39).

{am_table}

Seydel's original setup (plain CN on x in [-5, 5]) has errors
{", ".join(fmt(e) for e in am_err[names[3]])} on the same grids: a wider
x-interval spends nodes far from the strike, so the default here takes
L = max(1, 6 sigma sqrt(T) + |drift| T).

## Projected SOR vs Brennan–Schwartz

Same American put. PSOR uses the optimal SOR factor and warm start from the
previous time level, stopping tolerance 1e-12 (relative). Times in seconds
for the pure-Python kernels; with `pip install numba` the inner loops are JIT-compiled
and both solvers run much faster.

{psor_table}
"""
write_md("convergence.md", md)

# ----------------------------------------------------------------------------- figure
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(11, 4.2))
m_eu = np.array(eu_grids, float)
for (k, label), color, mk in zip(
    [("price", "price"), ("delta", "Δ"), ("gamma", "Γ"), ("theta", "Θ")],
    [BLUE, ORANGE, AQUA, VIOLET],
    ["o", "s", "^", "D"],
    strict=True,
):
    ax1.loglog(m_eu, eu_err[k], marker=mk, color=color, label=label)
guide = eu_err["price"][0] * (m_eu / m_eu[0]) ** -2
ax1.loglog(m_eu, guide * 3, ls="--", lw=1.2, color=MUTED, label="slope −2")
ax1.set(xlabel="grid size m = n", ylabel="absolute error at S = K",
        title="European put: Crank–Nicolson vs Black–Scholes")  # fmt: skip
ax1.legend(loc="lower left")

m_am = np.array(GRIDS, float)
ax2.loglog(m_am, am_err[names[0]], marker="o", color=BLUE, label="CN + Rannacher")
ax2.loglog(m_am, am_err[names[1]], marker="s", color=ORANGE, label="CN, no smoothing")
ax2.loglog(m_am, am_err[names[2]], marker="^", color=AQUA, label="fully implicit")
ax2.loglog(m_am[1:], extrap_err, marker="D", color=VIOLET, label="CN+R, extrapolated")
for p, y0 in ((1, am_err[names[2]][0] * 1.6), (2, am_err[names[0]][0] * 0.45)):
    ax2.loglog(m_am, y0 * (m_am / m_am[0]) ** -p, ls="--", lw=1.2, color=MUTED)
    ax2.annotate(f"slope −{p}", (m_am[-1], y0 * (m_am[-1] / m_am[0]) ** -p),
                 textcoords="offset points", xytext=(4, 0), color=INK_2, fontsize=8,
                 va="center")  # fmt: skip
ax2.set(xlabel="grid size m = n", ylabel="|V − V_ref| at S = K",
        title="American put (Seydel Ex. 1.6) vs BBSR binomial")  # fmt: skip
ax2.legend(loc="lower left")
save(fig, "convergence.png")
