"""Greeks Delta, Gamma, Theta from the grid, and the Rannacher effect.

* ``greeks.png`` — Delta, Gamma, Theta of the American put across S, with the
  European (Black–Scholes) curves for comparison and the exercise boundary.
* ``rannacher_gamma.png`` — Gamma near the strike with plain Crank–Nicolson
  vs Rannacher start-up, for a large ratio dtau/dx^2.
* ``results/greeks.md`` — Greeks at S = K: FD vs analytic (European) and vs
  bump-and-reprice on a binomial tree (American).

Run:  python scripts/greeks.py
"""

from __future__ import annotations

import numpy as np
from _common import AQUA, BLUE, INK_2, MUTED, ORANGE, md_table, plt, save, write_md

from americanfd import Option, binomial_price, bs_greeks, solve_fd

am = Option(K=50.0, T=5 / 12, r=0.1, sigma=0.4, kind="put")
eu = am.with_(style="european")

# ----------------------------------------------------------------------------- table
rows = []
S0 = 50.0
g_eu = solve_fd(eu, 800, 800).greeks(S0)
x_eu = bs_greeks(S0, eu)
for k in ("price", "delta", "gamma", "theta"):
    rows.append(["European", k, f"{getattr(g_eu, k):.6f}", f"{getattr(x_eu, k):.6f}",
                 f"{abs(getattr(g_eu, k) - getattr(x_eu, k)):.1e}"])  # fmt: skip

g_am = solve_fd(am, 800, 800).greeks(S0)
h, dt = 0.25, 1e-3
n_tree = 8000
up, mid, dn = (binomial_price(s, am, n=n_tree) for s in (S0 + h, S0, S0 - h))
later = binomial_price(S0, am.with_(T=am.T - dt), n=n_tree)
bump = {
    "price": mid,
    "delta": (up - dn) / (2 * h),
    "gamma": (up - 2 * mid + dn) / h**2,
    "theta": (later - mid) / dt,  # dV/dt: one step closer to expiry
}
for k in ("price", "delta", "gamma", "theta"):
    rows.append(["American", k, f"{getattr(g_am, k):.6f}", f"{bump[k]:.6f}",
                 f"{abs(getattr(g_am, k) - bump[k]):.1e}"])  # fmt: skip

write_md(
    "greeks.md",
    "# Greeks at S = K\n\nGenerated by `scripts/greeks.py`. Seydel Example 1.6 "
    "(K = 50, T = 5/12, r = 10%, σ = 40%), FD grid 800×800. Reference: Black–Scholes "
    f"formulas (European); bump-and-reprice on a BBSR tree with N = {n_tree}, "
    f"h = {h}, dt = {dt} (American). Theta is dV/dt per year.\n\n"
    + md_table(["style", "quantity", "finite differences", "reference", "abs diff"], rows),
)

# ----------------------------------------------------------------------------- greeks figure
res_am = solve_fd(am, 800, 800)
sf = res_am.exercise_boundary_t0
S = np.linspace(25.0, 90.0, 600)
ga, ge = res_am.greeks(S), bs_greeks(S, eu)

fig, axes = plt.subplots(1, 3, figsize=(12.5, 3.8))
titles = ("Delta Δ", "Gamma Γ", "Theta Θ = ∂V/∂t")
for ax, k, title in zip(axes, ("delta", "gamma", "theta"), titles, strict=True):
    ax.plot(S, getattr(ge, k), color=ORANGE, label="European (formula)")
    ax.plot(S, getattr(ga, k), color=BLUE, label="American (FD)")
    ax.axvline(sf, color=MUTED, lw=1)
    ax.set(title=title, xlabel="spot S", xlim=(25, 90))
axes[0].legend(loc="lower right")
axes[0].annotate("S_f", (sf, -0.95), xytext=(4, 0), textcoords="offset points", color=INK_2,
                 fontsize=8.5)  # fmt: skip
axes[1].annotate("Γ jumps at S_f:\nsmooth pasting keeps\nonly Δ continuous", (58, 0.040),
                 color=INK_2, fontsize=8)  # fmt: skip
fig.suptitle("American put, K = 50, T = 5/12, r = 10%, σ = 40% (t = 0)", color=INK_2,
             fontsize=10, y=1.02)  # fmt: skip
save(fig, "greeks.png")

# ----------------------------------------------------------------------------- Rannacher figure
short_eu = Option(K=100.0, T=0.25, r=0.05, sigma=0.2, kind="put", style="european")
m, n = 800, 25
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(11, 3.9))
for ax, opt, title in (
    (ax1, short_eu, "European put"),
    (ax2, short_eu.with_(style="american"), "American put"),
):
    pure = solve_fd(opt, m, n, rannacher=0, lcp="brennan-schwartz")
    smooth = solve_fd(opt, m, n, rannacher=2, lcp="brennan-schwartz")
    mask = (pure.S > 85) & (pure.S < 115)
    ax.plot(pure.S[mask], pure.gamma[mask], color=ORANGE, lw=1.4, label="Crank–Nicolson")
    ax.plot(smooth.S[mask], smooth.gamma[mask], color=BLUE, label="CN + Rannacher start-up")
    if opt.style == "european":
        Sx = np.linspace(85, 115, 400)
        ax.plot(Sx, bs_greeks(Sx, opt).gamma, color=AQUA, lw=1.2, ls="--", label="exact")
    else:
        impl = solve_fd(opt, m, n, theta=1.0, rannacher=0, lcp="brennan-schwartz")
        ax.plot(impl.S[mask], impl.gamma[mask], color=AQUA, lw=1.2, ls="--",
                label="fully implicit (θ = 1)")  # fmt: skip
        ax.annotate("ringing where the free\nboundary crossed nodes", (86, 0.085),
                    color=INK_2, fontsize=8)  # fmt: skip
        ax.legend(loc="lower right")
    ax.set(title=f"{title}: Γ near the strike", xlabel="spot S", ylim=(-0.12, 0.2))
ax1.legend(loc="upper left")
fig.suptitle(f"K = 100, T = 0.25, σ = 20%; grid m = {m}, n = {n} (Δτ/Δx² ≈ "
             f"{(0.5 * 0.2**2 * 0.25 / n) / (2 * 1.0 / m) ** 2:.0f})",
             color=INK_2, fontsize=10, y=1.02)  # fmt: skip
save(fig, "rannacher_gamma.png")
