"""How the relaxation factor omega affects projected SOR.

Average PSOR sweeps per time step as omega varies, for three grids with
different lam = dtau / dx^2, against the automatic choice (Young's optimal
omega for the unconstrained tridiagonal system, recomputed every step).

Finding: with a warm start from the previous time level a fixed omega of
1.2-1.4 beats Young's value when lam is moderate, but no fixed value is good
for every grid; Young's omega is the robust default.  Seydel (notes on §4.6)
recommends omega = 1, which is the slowest choice everywhere here.

Run:  python scripts/psor_omega.py
"""

from __future__ import annotations

import numpy as np
from _common import AQUA, BLUE, MUTED, ORANGE, md_table, plt, save, write_md

from americanfd import Option, solve_fd

am = Option(K=50.0, T=5 / 12, r=0.1, sigma=0.4, kind="put")
omegas = np.round(np.arange(1.0, 1.91, 0.1), 2)
grids = [(200, 200, AQUA), (800, 800, BLUE), (800, 100, ORANGE)]

fig, ax = plt.subplots(figsize=(7.4, 4.2))
rows = []
for m, n, color in grids:
    sweeps = [np.mean(solve_fd(am, m, n, omega=w).psor_sweeps) for w in omegas]
    auto = solve_fd(am, m, n)
    auto_sweeps = np.mean(auto.psor_sweeps)
    lam = (0.5 * am.sigma**2 * am.T / n) / (2 * auto.settings["half_width"] / m) ** 2
    ax.plot(omegas, sweeps, marker="o", ms=5, color=color, label=f"{m}×{n}, λ ≈ {lam:.2g}")
    ax.axhline(auto_sweeps, color=color, ls="--", lw=1.1)
    best = int(np.argmin(sweeps))
    best_txt = f"{sweeps[best]:.1f} (ω={omegas[best]})"
    rows.append([f"{m}×{n}", f"{lam:.2g}", f"{sweeps[0]:.1f}", best_txt, f"{auto_sweeps:.1f}"])
    print(rows[-1])

ax.set(xlabel="fixed relaxation factor ω", ylabel="mean PSOR sweeps per time step",
       yscale="log", title="Projected SOR: sweeps vs ω (dashed: automatic ω*)")  # fmt: skip
ax.plot([], [], ls="--", color=MUTED, lw=1.1, label="automatic ω* (same colour)")
ax.legend(loc="upper left", bbox_to_anchor=(1.01, 1.0))
save(fig, "psor_omega.png")

HEAD = ["grid m×n", "λ = Δτ/Δx²", "ω = 1 (Gauss–Seidel)", "best fixed ω", "automatic ω* (Young)"]
write_md(
    "psor_omega.md",
    "# PSOR relaxation factor\n\nGenerated by `scripts/psor_omega.py`. American put of "
    "Seydel Ex. 1.6, Crank–Nicolson + Rannacher, warm start, tolerance 1e-12. "
    "Mean sweeps per time step.\n\n"
    + md_table(HEAD, rows)
    + "\n\nNo fixed ω is good on every grid: 1.2–1.4 wins for moderate λ but is "
    "slow for large λ. Young's ω* stays within a factor of about 1.6 of the best "
    "fixed value on every grid and is the default.",
)
